export const CHANGE_USER_EMAIL = "CHANGE_USER_EMAIL";
export const CHANGE_PASSWORD = "CHANGE_PASSWORD";
export const CHANGE_VERIFICATION_PASSWORD = "CHANGE_VERIFICATION_PASSWORD";
export const SAVE_SELECTED_DAY = "SAVE_SELECTED_DAY";
export const SAVE_TODOS = "SAVE_TODOS";